filename: 'train'
features:
  - 'Pclass'
  - 'PassengerId'
  - 'Sex'
  - 'Age'
  - 'SibSp'
  - 'Parch'
  - 'Fare'
  - 'Embarked'
  - 'Survived'

features_input:
  - 'Pclass'
  - 'PassengerId'
  - 'Sex'
  - 'Age'
  - 'SibSp'
  - 'Parch'
  - 'Fare'
  - 'Embarked'



target_feature: 'Survived'